feature(i18n):add nested argument and string interpolation
abak-press/apress-handlebars-helpers pull request #1
Opened 2019-06-06 08:35 UTC by EgorOvechkin

[MINOR] Добавит возможность передавать булевый параметр,
позволяющий доставать строки из вложенных объектов.
Добавит возможность интерполировать параметры строки
заданные через %{param}.
Пример {{ i18n 'unique.locale.string.name' true email="some@mail.ru" }}

2019-06-06 08:37 UTC, EgorOvechkin commented
@buchenkona @idbolshakov

2019-06-06 08:53 UTC, buchenkowa approved these changes

2019-06-09 09:33 UTC, idbolshakov requested changes
а давай откажемся от параметра `nested` и по дефолту для всего будем пробовать искать вложенные значения? 

Конструкция немного упростится)

2019-06-10 06:01 UTC, EgorOvechkin commented
можно, только надо иметь в виду что на пц и близко пишут [такие локали](https://github.com/abak-press/blizko/blob/master/app/views/company_domain/require/_i18n.html.erb#L4), они перестанут работать если так сделать.

2019-06-10 15:55 UTC, EgorOvechkin commented
пока сделал отдельным коммитом.
:up:

2019-06-12 17:46 UTC, idbolshakov approved these changes
в package.json поменяй версию на 2.0.0 пожалуйста

2019-06-13 06:21 UTC, EgorOvechkin commented
:up:

2019-06-13 19:51 UTC, idbolshakov approved these changes

2019-06-13 19:51 UTC, merged